### ISSUE TITLE
[Chrome] Drop-down disappear after click on scroll

### ISSUE THREAD

**Issue by dgomesbr** [alexgorbatchev/jquery-textext#15] opened 2012-01-26 00:53 UTC
After clicking on the arrow to show the scroll it appears correctly, if try clicking on the scroll the drop-down options disappear.

**Comment by dgomesbr** [comment] 2012-01-26 01:01
I didn't look deep the code, but there's something to do on how the 

``` javascript
self.trigger(self.containerElement().is(':visible') ? EVENT_HIDE_DROPDOWN : EVENT_SHOW_DROPDOWN);
```

is treated.

**Comment by gerad** [comment] 2012-01-27 02:53
it's most likely because a click on the scrollbar defocuses the input in chrome, we've worked around this in other autocompletes by not listening to the blur event on the input, and instead trying to deduce it by listening to clicks on the body element and others

**Comment by dgomesbr** [comment] 2012-01-27 11:04
Cool, I don't know how to fix that, but are you able to reproduce it?

**Comment by gerad** [comment] 2012-01-27 17:21
I'm pretty sure https://github.com/alexgorbatchev/jquery-textext/pull/10 fixes it. - Gerad

**Comment by alexgorbatchev** [comment] 2012-02-02 22:18
Sounds like a duplicate of #4. I need to review and merge the pull request that fixes it.

**Closed as completed by alexgorbatchev** 2012-02-02 22:18 UTC
